# App configuration
VERSION: "0.3.2"
EXCLUDED_FILES:
  [
    ".*",
    "Thumbs.db",
    ".DS_Store",
    "._.DS_Store",
    ".localized",
    "desktop.ini",
    "*.pyc",
    "*.swx",
    "*.swp",
    "*~",
    "~$*",
    "NULLEXT",
  ]
APP_NAME: "frdr-encryption-client"
APP_AUTHOR: "Compute Canada"
TIMEZONE: "America/Regina"
APP_LOG_FILENAME: "frdr-encryption-client_log.txt"
GLOBUS_DATA_PUBLICATION_CLIENT_ID: "7dbc22b3-60c1-4e75-b148-3ee89f95792d"
GLOBUS_DATA_PUBLICATION_CLIENT_NAME: "DataPublication Client v0.1"
GLOBUS_LOGOUT_URL: "https://auth.globus.org/v2/web/logout"
FRDR_API_BASE_URL: "https://dev4-web-c1.frdr.ca/v1/api"
FRDR_API_LOGIN_TIMEOUT: 60
FRDR_PROFILE_URL: "https://dev4-web-c1.frdr.ca/repo/settings/sensitive"
FRDR_CONTACTUS_URL: "https://dev4-web-c1.frdr.ca/repo/contactus?locale="
FRDR_DEPOSIT_DASHBOARD_URL: "https://dev4-web-c1.frdr.ca/repo/PublishDashboard"

# Dataset key server configuration
VAULT_DATASET_KEY_PATH: "dataset"
VAULT_HOSTNAME: "https://frdrvault.net"
VAULT_CLIENT_LOGIN_REDIRECT_PORT_MIN: 8250
VAULT_CLIENT_LOGIN_REDIRECT_PORT_MAX: 8254
VAULT_LOGIN_TIMEOUT: 60

# Person key server configuration
VAULT_PUBLIC_KEY_PATH: "public_key"
VAULT_GENERATE_CERT_ROLE_NAME: "frdrvault-dot-net"
VAULT_GENERATE_CERT_COMMON_NAME: "test.frdrvault.net"
VAULT_GENERATE_CERT_MOUNT_NAME: "pki_int"
LOCAL_KEY_DIR_NAME: "frdr_keys"
LOCAL_PRIVATE_KEY_FILENAME: "private.key"
LOCAL_PUBLIC_KEY_FILENAME: "public.key"
